# http://www.doctrine-project.org/docs/orm/2.0/en/reference/yaml-mapping.html

Nutellove\JavascriptClassBundle\Entity\Ant:
  type: entity
  table: ant
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 50
      js: read
    size:
      type: integer
      default: 10
    is_hungry:
      type: boolean
      default: false
      js: rw
#  manyToOne:
#    anthill:
#      targetEntity: Anthill
#      inversedBy: ants

#  oneToOne:
#    address:
#      targetEntity: Address
#      joinColumn:
#        name: address_id
#        referencedColumnName: id
#  oneToMany:
#    phonenumbers:
#      targetEntity: Phonenumber
#      mappedBy: user
#      cascade: cascadePersist
#  manyToMany:
#    groups:
#      targetEntity: Group
#      joinTable:
#        name: cms_users_groups
#        joinColumns:
#          user_id:
#            referencedColumnName: id
#        inverseJoinColumns:
#          group_id:
#            referencedColumnName: id
#  lifecycleCallbacks:
#    prePersist: [ doStuffOnPrePersist, doOtherStuffOnPrePersistToo ]
#    postPersist: [ doStuffOnPostPersist ]
