
jsclass_entity_ant:
    pattern:  /jsclass/JavascriptClassBundle/Ant
    defaults: { _controller: JavascriptClassBundle:Entity\JavascriptClassBundle\Ant:index }

jsclass_entity_ant_load:
    pattern:  /jsclass/JavascriptClassBundle/Ant/load/{id}
    defaults: { _controller: JavascriptClassBundle:Entity\JavascriptClassBundle\Ant:load, _format: json }

jsclass_entity_ant_save:
    pattern:  /jsclass/JavascriptClassBundle/Ant/save
    defaults: { _controller: JavascriptClassBundle:Entity\JavascriptClassBundle\Ant:save, _format: json }
